### ISSUE TITLE
[agi_mopublic_pub]   - Self-intersection

### ISSUE THREAD

**Issue by Luescher** [sogis/gretljobs#522]
Grudstückbeschrieb geht nicht bei den Grundstücken z.B. CH788232067709 und CH357432890638. Problem "Self-intersection" 

```
[2020-01-07 13:46:37,601] ERROR in plot_info: (psycopg2.errors.InternalError_) 
lwgeom_intersection: GEOS Error: TopologyException: Input geom 0 is invalid: Self-intersection at 
or near point 2608701.2519999985 1228210.9569999997 at 2608701.2519999985 1228210.9569999997
[SQL: WITH bodenbedeckung AS (SELECT ST_Area(ST_Intersection(b.geometrie, g.geometrie)) AS b_area,ST_Area(g.geometrie) AS g_area,CASE WHEN b.art_txt = 'Liegenschaft' THEN 0 ELSE 1 END AS art, b.art_txt FROM         agi_mopublic_pub.mopublic_bodenbedeckung b JOIN agi_mopublic_pub.mopublic_grundstueck g ON ST_Intersects(b.geometrie, g.geometrie) 
AND NOT ST_Touches(b.geometrie, g.geometrie) WHERE g.egrid = %(egrid)s ) 
SELECT SUM(b_area) AS area, SUM(b_area/g_area) * 100 AS area_percent, art, art_txt FROM bodenbedeckung b GROUP BY art, art_txt ORDER BY area DESC;]
```
```
[2020-01-07 13:49:07,281] ERROR in plot_info: (psycopg2.errors.InternalError_) lwgeom_intersection: GEOS Error: TopologyException: Input geom 0 is invalid: Self-intersection at or near point 2630843.3380000009 1241234.3080000011 at 2630843.3380000009 1241234.3080000011
[SQL: WITH bodenbedeckung AS (SELECT ST_Area(ST_Intersection(b.geometrie, g.geometrie)) AS b_area,ST_Area(g.geometrie) AS g_area,CASE WHEN b.art_txt = 'Liegenschaft' THEN 0 ELSE 1 END AS art, b.art_txt FROM         agi_mopublic_pub.mopublic_bodenbedeckung b JOIN agi_mopublic_pub.mopublic_grundstueck g ON ST_Intersects(b.geometrie, g.geometrie) AND NOT ST_Touches(b.geometrie, g.geometrie) WHERE g.egrid = %(egrid)s ) SELECT SUM(b_area) AS area, SUM(b_area/g_area) * 100 AS area_percent, art, art_txt FROM bodenbedeckung b GROUP BY art, art_txt ORDER BY area DESC;]


```

**Comment by edigonzales** [comment]
Das Problem ist, dass die Funktion `ST_CurveToLine()` fehlerhafte Geometrien produziert. Die erste Idee mit `ST_MakeValid()` beim Datenumbau die Daten zu bereinigen, funktioniert auch nicht, weil das zu Mulitpolygonen und Geometrycollections führt. Die Geometrien sind aber per Modell nur Singlepolygone.

D.h. die Daten müssen bereits beim Importieren segmentiert werden. 

Grober Lösungsweg:

1. Neues Schema `agi_dm01avso24_strokearcs` mit `--strokeArcs` anlegen.
2. GRETL-Job für Bulk-Import der AV erstellen: `agi_dm01avso24`
3. Daten mit GRETL-Job importieren
4.  Schema umbenennen
5. MOpublic-GRETL-Job ausführen und kontrollieren, ob Problem gelöst.
6. `ST_CurveToLine` aus MOpublic- und OEREB-GRETL-Jobs entfernen, da nicht mehr benötigt.

**Comment by edigonzales** [comment]
"Bugfix" auf Prod ausgerollt: https://geoweb.rootso.org/redmine/issues/3900

Ticket für Entfernen der unnötigen Funktionen erstellt:
- https://github.com/sogis/gretljobs/issues/529
- https://github.com/sogis/oereb-gretljobs/issues/89
