### ISSUE TITLE
[arp_fledermaus] validateCsv vor truncateTable

### ISSUE THREAD

**Issue by schmandr** [sogis/gretljobs#721]
Ist mir zufällig aufgefallen: Es wäre wohl sinnvoll, zuerst das CSV zu validieren, und nur dann die Tabelle zu leeren, wenn die Validierung erfolgreich war.

https://github.com/sogis/gretljobs/blob/4cd28f90825fc47b49d571ccfe058c72c236ddbe/arp_fledermaus/build.gradle#L78

**Comment by edigonzales** [comment]
fixed 3d80230c010dde0f7875f484af2e42c5f8a150e7
