### ISSUE TITLE
Anpassung start-gretl.sh

### ISSUE THREAD

**Issue by pfeimich** [sogis/gretljobs#97]
Im start-gretl.sh müssen die dbParameter angepasst werden, da diese mit den neuen Parametern nicht mehr funktionieren. Das es zukünftig mehr als nur source und target DB gibt wäre es vermutlich sinnvoll die Paramter dynamisch dem Skript zu übergeben

**Comment by schmandr** [comment]
Ist erledigt mit https://github.com/sogis/gretljobs/commit/778311015e8afe6d61da839ee42aa6a1cfd36b1a. Wobei das dynamische Übergeben ans Skript noch nicht umgesetzt ist. Ich weiss im Moment noch nicht, wie das zu lösen ist.

**Comment by schmandr** [comment]
Für das dynamische Übergeben könnte eine mögliche Lösung sein, dass die Env-Variablen z.B. so definiert werden: `ORG_GRADLE_PROJECT_dbUriPub`. In diesem Beispiel ist ihr Wert dann im Skript mit der Skript-Variablen `dbUriPub` abrufbar.
